sudo: true

os:
    - linux
#    - osx

language: cpp

python: '3.6'

compiler:
#    - clang
    - gcc

# addons:
#   apt:
#     packages:
#         - ninja=1.9.0

before_install:

#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --with-toolchain llvm; fi

    # At the time of writing this config file, the default image was Ubuntu 14.04 which had Ninja 1.3.x installed. Meson requires >= 1.5.
    - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip && sudo unzip ninja-linux.zip -d /usr/local/bin/ && sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force
    - /usr/bin/ninja --version

    # Workaround for pip3. Without the Pyenv line, build fails because both versions 3.6 and 3.6.3 are available.
    - pyenv global system 3.6
    - pip3 install meson
    - meson --version

    # Update the apt-get repos.
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
#    - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
    - if [ "$CXX" == "clang++" ]; then sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"; fi
#    - sudo add-apt-repository -y ppa:mhier/libboost-latest
    - sudo apt-get -qq update
#    - sudo apt-get install ninja-build libboost-all-dev
    - sudo apt-get install ninja-build
# libboost1.68
# libboost1.67 libboost-all-dev
    - wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz
    - tar -xf boost_1_67_0.tar.gz
    - mkdir -p boost_1_67_0/include && mv boost_1_67_0/boost boost_1_67_0/include/
    - export BOOST_ROOT=$(pwd)/boost_1_67_0/

    # Install packages for GCC.
    - if [ "$CXX" == "g++" ]; then sudo apt-get install g++-8; fi
    - if [ "$CXX" == "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi
    # That line does not happen. I guess apt-get updated $CXX.

    # Install packages for Clang.
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-4.0.1 lldb-4.0; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-4.0"; fi
    - export CXX

install:
    - g++ --version
    - $CXX --version
    - make build
    - git -C subprojects/pbcopper rev-parse HEAD
    - meson subprojects update
    - git -C subprojects/pbcopper rev-parse HEAD
    - make

script:
    - build/tests_raptor
    - make cram

notifications:
    email:
        on_success: change
        on_failure: always
