#!/usr/bin/env bash

###################################
### This script is a workaround
### to run Cram tests, without actually
### installing the Python package.
### Based on: https://github.com/PacificBiosciences/unanimity/blob/develop/scripts/cram
###################################

CRAM_SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
PROJECT_DIR=${CRAM_SCRIPT_PATH}/../
BIN_DIR=${CRAM_SCRIPT_PATH}/../install/bin/
CRAM_DIR=${PROJECT_DIR}/third-party/cram/
LD_LIBRARY_PATH=${BIN_DIR}/../lib64:${BIN_DIR}/../lib:${LD_LIBRARY_PATH}
export PROJECT_DIR
export CRAM_DIR
export BIN_DIR
export LD_LIBRARY_PATH

# if we have cram already, use that
if [[ -x "$(which cram)" ]]; then
    exec cram "$@"
fi

exec env PYTHONPATH=$CRAM_DIR $CRAM_DIR/scripts/cram "$@"
